#!/usr/bin/env node
import { spawn, spawnSync } from "node:child_process";
import { chmod, mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL("..", import.meta.url)));
const image = "dejaml/python-cpu:0.1.0";
const minimumNodeMajor = 24;

function heading(message) {
  process.stdout.write(`\n==> ${message}\n`);
}

function fail(message) {
  process.stderr.write(`\nBOOTSTRAP FAILED: ${message}\n`);
  process.exit(1);
}

function commandAvailable(command, args = ["--version"]) {
  const result = spawnSync(command, args, { cwd: root, encoding: "utf8", stdio: "pipe" });
  return result.status === 0;
}

async function run(command, args, options = {}) {
  await new Promise((resolvePromise, rejectPromise) => {
    const child = spawn(command, args, {
      cwd: root,
      env: { ...process.env, ...(options.env ?? {}) },
      stdio: "inherit",
    });
    child.on("error", rejectPromise);
    child.on("close", (code) => {
      if (code === 0) resolvePromise();
      else rejectPromise(new Error(`${command} exited with status ${String(code)}`));
    });
  });
}

function capture(command, args) {
  const result = spawnSync(command, args, { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  if (result.status !== 0) throw new Error(result.stderr.trim() || `${command} exited with status ${String(result.status)}`);
  return result.stdout.trim();
}

async function downloadPaper() {
  const manifest = JSON.parse(await readFile(join(root, "cases/urban-land-cover/case.json"), "utf8"));
  const destination = join(root, "artifacts/demo/paper.pdf");
  const existing = await readFile(destination).catch(() => null);
  if (existing?.subarray(0, 5).toString("ascii") === "%PDF-") return destination;
  const response = await fetch(manifest.paper.pdfUrl, { redirect: "follow", signal: AbortSignal.timeout(30_000) });
  if (!response.ok) throw new Error(`paper download returned HTTP ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  if (bytes.length > 20 * 1024 * 1024 || bytes.subarray(0, 5).toString("ascii") !== "%PDF-") {
    throw new Error("paper download was not a valid PDF under 20 MB");
  }
  await mkdir(join(root, "artifacts/demo"), { recursive: true, mode: 0o700 });
  await writeFile(destination, bytes, { mode: 0o600 });
  return destination;
}

try {
  const nodeMajor = Number(process.versions.node.split(".")[0]);
  if (!Number.isInteger(nodeMajor) || nodeMajor < minimumNodeMajor) {
    fail(`Node.js ${minimumNodeMajor}+ is required; found ${process.version}.`);
  }
  if (!commandAvailable("npm")) fail("npm is required.");
  if (!commandAvailable("python3")) fail("Python 3 is required to fetch the checksum-pinned dataset.");
  if (!commandAvailable("docker", ["info"])) fail("Docker is required and its Linux engine must be running.");

  heading("Installing locked JavaScript dependencies");
  await run("npm", ["ci"]);

  heading("Building, type-checking, and testing the repository");
  await run("npm", ["run", "check"]);

  heading("Fetching and verifying the curated public dataset");
  await run("python3", ["cases/urban-land-cover/fetch_data.py"]);

  heading("Building the pinned local CPU lab image");
  await run("docker", [
    "build",
    "--provenance=false",
    "--file",
    "lab-images/python-cpu/Dockerfile",
    "--tag",
    image,
    ".",
  ]);
  const imageId = capture("docker", ["image", "inspect", image, "--format", "{{.Id}}"]);
  if (!/^sha256:[a-f0-9]{64}$/u.test(imageId)) throw new Error(`Docker returned an invalid image ID: ${imageId}`);

  heading("Running the real curated paper experiment in the disposable lab");
  await run("npm", ["run", "verify:curated", "--workspace", "@dejaml/lab-manager"], {
    env: { DEJAML_EXPECTED_IMAGE_ID: imageId },
  });

  heading("Preparing the example paper and live web build");
  const paperPath = await downloadPaper();
  await run("npm", ["run", "build", "--workspace", "@dejaml/web"], {
    env: { VITE_DEJAML_API: "live" },
  });

  const localEnvironment = [
    "# Generated by npm run bootstrap. Set the model and supply the key in the server environment.",
    `DEJAML_EXPECTED_IMAGE_ID=${imageId}`,
    "DEJAML_MODEL_BASE_URL=https://api.openai.com/v1",
    "DEJAML_MODEL=",
    "DEJAML_LAB_AGENT_ENABLED=1",
    "HOST=127.0.0.1",
    "PORT=8787",
    "",
  ].join("\n");
  const environmentPath = join(root, ".env.local");
  await writeFile(environmentPath, localEnvironment, { mode: 0o600 });
  await chmod(environmentPath, 0o600);

  const resultPath = join(root, "cases/urban-land-cover/artifacts/result.json");
  const result = JSON.parse(await readFile(resultPath, "utf8"));
  const resultInfo = await stat(resultPath);

  heading("Bootstrap complete");
  process.stdout.write(`Verified result: ${result.metrics.accuracyPercent}%\n`);
  process.stdout.write(`Paper: ${paperPath}\n`);
  process.stdout.write(`Result: ${resultPath} (${resultInfo.size} bytes)\n`);
  process.stdout.write(`Local image: ${imageId}\n\n`);
  process.stdout.write("Explore the labelled replay UI:\n  npm run demo:replay\n\n");
  process.stdout.write("Set DEJAML_MODEL in .env.local and DEJAML_MODEL_API_KEY in the server environment, then run npm run start:local.\n");
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
}
