// Reading and updating `.env.local` without ever losing or exposing a provider key.
//
// `npm run bootstrap` owns only machine-local values it generates (the verified
// lab image ID) and a few defaults it adds when they are missing (HOST, PORT,
// DEJAML_LAB_AGENT_ENABLED). Every other line - provider keys, model lists,
// comments, custom ports - is kept byte for byte, in place. Errors name a line
// number, never a line's content, so a malformed key line is never echoed.
import { randomBytes } from "node:crypto";
import { chmod, lstat, open, readFile, rename, unlink } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

/** Values bootstrap generates for this machine; always updated. */
export const GENERATED_KEYS = Object.freeze(["DEJAML_EXPECTED_IMAGE_ID"]);

/** Defaults bootstrap adds only when the file does not set them (a custom HOST or PORT is kept). */
export const DEFAULT_VALUES = Object.freeze({
  DEJAML_LAB_AGENT_ENABLED: "1",
  HOST: "127.0.0.1",
  PORT: "8787",
});

const HEADER = [
  "# Generated by npm run bootstrap, which only updates DEJAML_EXPECTED_IMAGE_ID and adds missing defaults;",
  "# every other line is kept. Model keys may be added here or in the server environment:",
  "# DEJAML_ANTHROPIC_API_KEY, or DEJAML_OPENAI_API_KEY with DEJAML_OPENAI_MODELS (see .env.example).",
  "# This file is mode 0600 and git-ignored. Uploaders never supply keys; without one, no provider is offered.",
];

const NAME = /^[A-Za-z_][A-Za-z0-9_]*$/u;
const IMAGE_ID = /^sha256:[a-f0-9]{64}$/u;
const ENV_MODE = 0o600;

/** Names that hold credentials; their values are never printed. */
export function isSecretName(name) {
  return /(?:_API_KEY|_TOKEN|_SECRET|_PASSWORD|_CREDENTIALS?)$/u.test(name) || /^(?:AWS_|ANTHROPIC_API|OPENAI_API)/u.test(name);
}

export class EnvLocalError extends Error {
  constructor(message) {
    super(message);
    this.name = "EnvLocalError";
  }
}

function splitLine(rawLine) {
  const line = rawLine.trim();
  if (!line || line.startsWith("#")) return null;
  const body = line.startsWith("export ") ? line.slice("export ".length).trimStart() : line;
  const separator = body.indexOf("=");
  if (separator <= 0) return { error: true };
  const name = body.slice(0, separator).trim();
  if (!NAME.test(name)) return { error: true };
  return { name, value: body.slice(separator + 1) };
}

/**
 * Parses `.env.local` (`NAME=value` lines, optional `export `, `#` comments).
 * Values are taken verbatim. A malformed line throws an EnvLocalError that
 * names only its line number.
 */
export function parseEnvLocal(text) {
  const values = {};
  text.split(/\r?\n/u).forEach((rawLine, index) => {
    const parsed = splitLine(rawLine);
    if (parsed === null) return;
    if (parsed.error) {
      throw new EnvLocalError(`.env.local line ${index + 1} is not NAME=value (its content is not shown because it may hold a key)`);
    }
    values[parsed.name] = parsed.value;
  });
  return values;
}

function setLine(name, value) {
  if (/[\r\n]/u.test(value)) throw new EnvLocalError(`${name} must be a single line`);
  return `${name}=${value}`;
}

/**
 * Returns the new `.env.local` text: `existing` (or null for a new file) with
 * every generated key set to `generated[name]`, missing defaults appended, and
 * all other lines unchanged.
 */
export function mergeEnvLocal(existing, generated) {
  for (const name of GENERATED_KEYS) {
    if (typeof generated?.[name] !== "string") throw new EnvLocalError(`${name} is required`);
  }
  if (!IMAGE_ID.test(generated.DEJAML_EXPECTED_IMAGE_ID)) throw new EnvLocalError("DEJAML_EXPECTED_IMAGE_ID must be sha256:<64 hex>");
  const current = existing === null ? {} : parseEnvLocal(existing);
  const lines = existing === null ? [...HEADER] : existing.replace(/\r?\n$/u, "").split(/\r?\n/u);
  const output = lines.map((rawLine) => {
    const parsed = splitLine(rawLine);
    if (parsed && !parsed.error && GENERATED_KEYS.includes(parsed.name)) return setLine(parsed.name, generated[parsed.name]);
    return rawLine;
  });
  for (const name of GENERATED_KEYS) {
    if (!(name in current)) output.push(setLine(name, generated[name]));
  }
  for (const [name, value] of Object.entries(DEFAULT_VALUES)) {
    if (!(name in current)) output.push(setLine(name, value));
  }
  return `${output.join("\n")}\n`;
}

/** Reads `.env.local`, or null when it does not exist. Anything but a regular file is refused. */
export async function readEnvLocal(path) {
  const info = await lstat(path).catch((error) => {
    if (error?.code === "ENOENT") return null;
    throw error;
  });
  if (info === null) return null;
  if (!info.isFile())
    throw new EnvLocalError(`${basename(path)} must be a regular file (not a symlink or directory); it was left unchanged`);
  return readFile(path, "utf8");
}

/**
 * Writes `text` atomically: a 0600 temporary file in the same directory,
 * flushed, then renamed over `path`. The temporary file is removed on failure.
 */
export async function writeEnvLocalAtomic(path, text) {
  const temporary = join(dirname(path), `.${basename(path)}.${process.pid}.${randomBytes(6).toString("hex")}.tmp`);
  let handle = null;
  try {
    handle = await open(temporary, "wx", ENV_MODE);
    await handle.writeFile(text, "utf8");
    await handle.sync();
    await handle.close();
    handle = null;
    // Independent of the umask.
    await chmod(temporary, ENV_MODE);
    await rename(temporary, path);
  } catch (error) {
    if (handle !== null) await handle.close().catch(() => undefined);
    await unlink(temporary).catch(() => undefined);
    throw error;
  }
}

/** Reads, merges and atomically writes `.env.local`; returns the names (never values) of the credentials it kept. */
export async function updateEnvLocal(path, generated) {
  const existing = await readEnvLocal(path);
  const next = mergeEnvLocal(existing, generated);
  await writeEnvLocalAtomic(path, next);
  return {
    created: existing === null,
    keptSecrets: Object.keys(parseEnvLocal(next)).filter(isSecretName).sort(),
  };
}
