// Run with: node --test scripts/env-local.test.mjs
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, test } from "node:test";

import {
  CHEAPER_INFERENCE_DEFAULTS,
  EnvLocalError,
  mergeEnvLocal,
  parseEnvLocal,
  readEnvLocal,
  updateEnvLocal,
  writeEnvLocalAtomic,
} from "./env-local.mjs";

// Obviously fake fixtures: never real keys.
const ANTHROPIC_KEY = "sk-ant-test-FIXTURE-0000000000000000";
const OPENAI_KEY = "sk-test-FIXTURE-openai-0000000000000000";
const CHEAPER_KEY = "ci-test-key-000000";
// What bootstrap appends to a file that has neither Cheaper Inference line.
const CHEAPER_LINES = `${CHEAPER_INFERENCE_DEFAULTS.note}\nDEJAML_CHEAPER_INFERENCE_MODELS=claude-sonnet-5.5\n# DEJAML_CHEAPER_INFERENCE_API_KEY=\n`;
const OLD_ID = `sha256:${"0".repeat(64)}`;
const NEW_ID = `sha256:${"1".repeat(64)}`;

const roots = [];
after(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

function directory() {
  const root = mkdtempSync(join(tmpdir(), "dejaml-env-local-"));
  roots.push(root);
  return root;
}

const EXISTING = [
  "# my local settings",
  `DEJAML_EXPECTED_IMAGE_ID=${OLD_ID}`,
  `DEJAML_ANTHROPIC_API_KEY=${ANTHROPIC_KEY}`,
  "DEJAML_ANTHROPIC_MODELS=claude-opus-5-5,claude-sonnet-5-5",
  `export DEJAML_OPENAI_API_KEY=${OPENAI_KEY}`,
  "DEJAML_OPENAI_MODELS=gpt-test-a,gpt-test-b",
  "DEJAML_LAB_AGENT_ENABLED=1",
  "HOST=127.0.0.1",
  "PORT=9999",
  "",
].join("\n");

test("a new file gets the generated image ID and defaults, and no key", () => {
  const text = mergeEnvLocal(null, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
  assert.deepEqual(parseEnvLocal(text), {
    DEJAML_EXPECTED_IMAGE_ID: NEW_ID,
    DEJAML_LAB_AGENT_ENABLED: "1",
    HOST: "127.0.0.1",
    PORT: "8787",
    DEJAML_CHEAPER_INFERENCE_MODELS: "claude-sonnet-5.5",
  });
  assert.match(text, /^# Generated by npm run bootstrap/u);
  // Only a commented placeholder names a key; no key line is set.
  assert.doesNotMatch(text, /^[^#\n]*API_KEY=/mu);
  assert.ok(text.endsWith(`\n${CHEAPER_LINES}`));
  assert.match(text, /NOT the official Anthropic API; zero-data-retention is disabled/u);
});

test("preserves Anthropic and OpenAI keys and model lists byte for byte; updates only the image ID", () => {
  const text = mergeEnvLocal(EXISTING, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
  // Every existing line is kept byte for byte; only the missing Cheaper Inference defaults are appended.
  assert.equal(text, EXISTING.replace(OLD_ID, NEW_ID) + CHEAPER_LINES);
  const values = parseEnvLocal(text);
  assert.equal(values.DEJAML_ANTHROPIC_API_KEY, ANTHROPIC_KEY);
  assert.equal(values.DEJAML_ANTHROPIC_MODELS, "claude-opus-5-5,claude-sonnet-5-5");
  assert.equal(values.DEJAML_OPENAI_API_KEY, OPENAI_KEY);
  assert.equal(values.DEJAML_OPENAI_MODELS, "gpt-test-a,gpt-test-b");
  // A custom port is the user's choice, not a generated value.
  assert.equal(values.PORT, "9999");
  // Idempotent.
  assert.equal(mergeEnvLocal(text, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID }), text);
});

test("adds missing generated values and defaults after the user's own lines", () => {
  const userOnly = `DEJAML_OPENAI_API_KEY=${OPENAI_KEY}\nDEJAML_OPENAI_MODELS=gpt-test-a`;
  const text = mergeEnvLocal(userOnly, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
  assert.equal(
    text,
    `${userOnly}\nDEJAML_EXPECTED_IMAGE_ID=${NEW_ID}\nDEJAML_LAB_AGENT_ENABLED=1\nHOST=127.0.0.1\nPORT=8787\n${CHEAPER_LINES}`,
  );
});

test("adds the Cheaper Inference model default without touching an existing key line, set or commented", () => {
  for (const keyLine of [
    `DEJAML_CHEAPER_INFERENCE_API_KEY=${CHEAPER_KEY}`,
    `export DEJAML_CHEAPER_INFERENCE_API_KEY=${CHEAPER_KEY}`,
    "# DEJAML_CHEAPER_INFERENCE_API_KEY=",
  ]) {
    const existing = `${EXISTING}${keyLine}\n`;
    const text = mergeEnvLocal(existing, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
    assert.equal(
      text,
      `${existing.replace(OLD_ID, NEW_ID)}${CHEAPER_INFERENCE_DEFAULTS.note}\nDEJAML_CHEAPER_INFERENCE_MODELS=claude-sonnet-5.5\n`,
    );
    assert.equal(text.split(/\n/u).filter((line) => line.includes("DEJAML_CHEAPER_INFERENCE_API_KEY")).length, 1);
    // Idempotent.
    assert.equal(mergeEnvLocal(text, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID }), text);
  }
  // An administrator's own model line is kept as it is (the server validates it), and nothing is added.
  const own = `${EXISTING}DEJAML_CHEAPER_INFERENCE_MODELS=claude-sonnet-5.5\n# DEJAML_CHEAPER_INFERENCE_API_KEY=\n`;
  assert.equal(mergeEnvLocal(own, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID }), own.replace(OLD_ID, NEW_ID));
});

test("reports a Cheaper Inference key by name only, never its value", async () => {
  const path = join(directory(), ".env.local");
  writeFileSync(path, `${EXISTING}DEJAML_CHEAPER_INFERENCE_API_KEY=${CHEAPER_KEY}\n`, { mode: 0o600 });
  const result = await updateEnvLocal(path, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
  assert.deepEqual(result, {
    created: false,
    keptSecrets: ["DEJAML_ANTHROPIC_API_KEY", "DEJAML_CHEAPER_INFERENCE_API_KEY", "DEJAML_OPENAI_API_KEY"],
  });
  assert.doesNotMatch(JSON.stringify(result), /ci-test-key|FIXTURE/u);
  assert.equal(parseEnvLocal(readFileSync(path, "utf8")).DEJAML_CHEAPER_INFERENCE_API_KEY, CHEAPER_KEY);
});

test("refuses a malformed file or value without echoing any line", () => {
  const malformed = `DEJAML_EXPECTED_IMAGE_ID=${OLD_ID}\nDEJAML_ANTHROPIC_API_KEY ${ANTHROPIC_KEY}\n`;
  for (const action of [() => parseEnvLocal(malformed), () => mergeEnvLocal(malformed, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID })]) {
    assert.throws(action, (error) => {
      assert.ok(error instanceof EnvLocalError);
      assert.match(error.message, /line 2/u);
      assert.doesNotMatch(error.message, /sk-ant|FIXTURE|ANTHROPIC/u);
      return true;
    });
  }
  assert.throws(() => mergeEnvLocal(null, { DEJAML_EXPECTED_IMAGE_ID: `${NEW_ID}\nDEJAML_X=1` }), EnvLocalError);
  assert.throws(() => mergeEnvLocal(null, {}), EnvLocalError);
});

test("updateEnvLocal keeps both providers, writes 0600 atomically and reports names only", async () => {
  const root = directory();
  const path = join(root, ".env.local");
  writeFileSync(path, EXISTING, { mode: 0o644 });
  const result = await updateEnvLocal(path, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID });
  assert.deepEqual(result, { created: false, keptSecrets: ["DEJAML_ANTHROPIC_API_KEY", "DEJAML_OPENAI_API_KEY"] });
  assert.doesNotMatch(JSON.stringify(result), /FIXTURE/u);
  assert.equal(readFileSync(path, "utf8"), EXISTING.replace(OLD_ID, NEW_ID) + CHEAPER_LINES);
  if (process.platform !== "win32") assert.equal(statSync(path).mode & 0o777, 0o600);
  // No temporary file is left next to it.
  assert.deepEqual(readdirSync(root), [".env.local"]);

  const fresh = join(directory(), ".env.local");
  assert.deepEqual(await updateEnvLocal(fresh, { DEJAML_EXPECTED_IMAGE_ID: NEW_ID }), { created: true, keptSecrets: [] });
  if (process.platform !== "win32") assert.equal(statSync(fresh).mode & 0o777, 0o600);
});

test("a failed write leaves the original file untouched and no temporary file", async () => {
  const root = directory();
  const path = join(root, ".env.local");
  writeFileSync(path, EXISTING, { mode: 0o600 });
  // Renaming a file over a directory fails after the temporary file was written.
  const blocked = join(root, "blocked");
  mkdirSync(blocked);
  await assert.rejects(writeEnvLocalAtomic(blocked, "X=1\n"));
  assert.equal(readFileSync(path, "utf8"), EXISTING);
  assert.deepEqual(readdirSync(root).sort(), [".env.local", "blocked"]);
});

test("refuses a symlinked .env.local instead of replacing it", { skip: process.platform === "win32" }, async () => {
  const root = directory();
  writeFileSync(join(root, "elsewhere"), EXISTING);
  symlinkSync(join(root, "elsewhere"), join(root, ".env.local"));
  await assert.rejects(readEnvLocal(join(root, ".env.local")), EnvLocalError);
  await assert.rejects(updateEnvLocal(join(root, ".env.local"), { DEJAML_EXPECTED_IMAGE_ID: NEW_ID }), EnvLocalError);
  assert.equal(readFileSync(join(root, "elsewhere"), "utf8"), EXISTING);
});
